- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  vars:
    ansible_user: ubuntu  # Specify the correct user
    docker_image_version: "latest"  # Replace with your desired version if needed
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      docker_container:
        name: finance_me
        image: "rajesh159951/finance:{{ docker_image_version }}"
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
