---
- hosts: test
  become: yes  # Use sudo for the tasks
  tasks:
    - name: Update apt package index
      command: apt-get update

    - name: Install Docker
      command: apt-get install -y docker.io

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes  # Ensure Docker starts on boot

    - name: Pull Docker image
      command: docker pull rajesh159951/finance:latest
      ignore_errors: yes  # Ignore errors if the image is already present

    - name: Run Docker container
      command: docker run -d --name finance -p 8080:8080 rajesh159951/finance:latest
      ignore_errors: yes  # Ignore errors if the container is already running
