- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks: 
    - name: Updating apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: "rajesh159951/finance:{{ build_id }}"
        pull: yes
      vars:
        build_id: "{{ lookup('env', 'BUILD_ID') }}"  # Gets the BUILD_ID from the environment

    - name: Run Docker container
      docker_container:
        name: finance
        image: "rajesh159951/finance:{{ build_id }}"
        state: started
        ports:
          - "8080:8080"
