- hosts: test
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Run Docker container
      docker_container:
        name: finance
        image: rajesh159951/finance:latest
        state: started
        ports:
          - "8080:8080"
